name: Weekly Beta Release

on:
  schedule:                       # every Thursday 03:00 UTC
    - cron: '0 3 * * 4'
  workflow_dispatch:              # manual trigger button

env:
  CI: true

jobs:
  beta-publish:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:

      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, registry-url: 'https://registry.npmjs.org/' }

      - run: pnpm install --frozen-lockfile

      - name: Publish weekly beta
        run: |
          # enter prerelease mode
          npx changeset pre enter beta

          # bump versions
          npx changeset version

          # your normal build (if needed)
          pnpm run build

          # publish to npm with dist-tag "beta"
          npx changeset publish --tag beta

          # leave prerelease mode so mainline releases stay clean
          npx changeset pre exit

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}